### ISSUE TITLE
Typo: Style Guide does not follow style guide: "Open API Initiative" vs "OpenAPI Initiative"

### ISSUE THREAD

**Issue by JohnLBevan** [OAI/OpenAPI-Style-Guide#2]
On: https://github.com/OAI/OpenAPI-Style-Guide
Under: The Initiative Name and Usage
The term "Open API Initiative" is used, though in the same sentence the rules state that there should be only 1 space (i.e. presumably it should be "OpenAPI Initiative" to be in line with the format used for "OpenAPI Specification").

**Comment by webron** [comment]
Actually, it's supposed to contain TWO spaces as corrected by #1. It is indeed `Open API Initiative` and `OpenAPI Specification`.
