### ISSUE TITLE
No XML attribute generated for attribute

### ISSUE THREAD

**Issue by JoopBL** [OAI/OpenAPI-Style-Guide#4]
I have the following XML:
`  <xs:element name="CancelRequest" nillable="true" type="CancelRequest" />
<xs:complexType name="CancelRequest">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="1" name="OrderID" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="version" type="xs:string" />
  </xs:complexType>
`
The corresponding Java class has ben generated using xjc:
`@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancelRequest", propOrder = {
    "orderID"
})
@XmlRootElement(name = "CancelRequest")
public class CancelRequest
    implements Serializable, ToString
{

    private final static long serialVersionUID = -1L;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlAttribute(name = "version")
    protected String version;

rest of class are getters and setters`

The code generated by Swagger is 
`   "CancelRequest": {
      "type": "object",
      "required": [
        "orderID"
      ],
      "properties": {
        "orderID": {
          "type": "string",
          "xml": {
            "name": "OrderID"
          }
        },
        "version": {
          "type": "string"
        }
      },
      "xml": {
        "name": "CancelRequest"
      }
    },`

There are no XML Object values generated for version. I would have expected here:
`          "xml": {
            "attribute":true
          }`
Since version is an attribute.

**Comment by fehguy** [comment]
Looks to me like this should be opened on swagger-core, which is an implementation of the spec.
