### ISSUE TITLE
Button to validate/download OpenAPI spec?

### ISSUE THREAD

**Issue by ksavenkov** [OAI/OpenAPI-Style-Guide#5]
Is there OpenAPI analogue to the Swagger validate button? Or currently the Swagger one should be used?

<img width="101" alt="screen shot 2017-04-12 at 22 00 20" src="https://cloud.githubusercontent.com/assets/1893114/24974666/9ac8c706-1fcb-11e7-9dad-5070d2f5d8b5.png">

**Comment by earth2marsh** [comment]
There is no official validation tooling, though our charter does allow for that. Now that the v3 spec is released, this is something we'll consider, but it may be one of those things that the community rises to provide or that we end up with multiple validation projects (which has pros and cons!).
